"""Pre-market report prompts."""
from .hidden_layer import HIDDEN_LAYER_PROMPT
from .layers import (
    LAYER_0_1_PROMPT,
    LAYER_2_3_PROMPT,
    LAYER_4_5_PROMPT,
    NEWS_SUMMARY_PROMPT,
)
from .v3 import PRE_MARKET_V3_PROMPT
from .v4 import (
    HIDDEN_LAYER_PROMPT as V4_HIDDEN_LAYER_PROMPT,
    NEWS_ANALYSIS_PROMPT,
    CORE_BRIEFING_PROMPT,
    PORTFOLIO_DISCOVERY_PROMPT,
)

__all__ = [
    "HIDDEN_LAYER_PROMPT",
    "LAYER_0_1_PROMPT",
    "LAYER_2_3_PROMPT",
    "LAYER_4_5_PROMPT",
    "NEWS_SUMMARY_PROMPT",
    "PRE_MARKET_V3_PROMPT",
    "V4_HIDDEN_LAYER_PROMPT",
    "NEWS_ANALYSIS_PROMPT",
    "CORE_BRIEFING_PROMPT",
    "PORTFOLIO_DISCOVERY_PROMPT",
]
